DROP TABLE IF EXISTS home_by_m;
DROP TABLE IF EXISTS visiting_by_m;
DROP TABLE IF EXISTS total_by_month;

CREATE TABLE home_by_m AS
    SELECT home_team AS team, 
        EXTRACT(YEAR FROM game_date) AS seas_yr, 
        EXTRACT(MONTH FROM game_date) AS seas_mon, 
        count(*) AS gp, 
        sum(visiting_score) AS ra, 
        sum(home_score) AS rs, 
        sum(3 * ceil((game_len_outs::float / 3) / 2)) AS outs, 
        sum(game_len_outs - 3 * ceil((game_len_outs::float / 3) / 2)) as outs_a,
        sum(3 * ceil((game_len_outs::float / 3) / 2)) / 3 AS ip,
        sum(game_len_outs - 3 * ceil((game_len_outs::float / 3) / 2)) / 3 AS ip_a,
        sum(game_time_minutes) AS game_time_minutes,
        sum(visiting_score_inning_1) AS ra_inn_1,
        sum(visiting_score_inning_2) AS ra_inn_2,
        sum(visiting_score_inning_3) AS ra_inn_3,
        sum(visiting_score_inning_4) AS ra_inn_4,
        sum(visiting_score_inning_5) AS ra_inn_5,
        sum(visiting_score_inning_6) AS ra_inn_6,
        sum(visiting_score_inning_7) AS ra_inn_7,
        sum(visiting_score_inning_8) AS ra_inn_8,
        sum(visiting_score_inning_9) AS ra_inn_9,
        sum(home_score_inning_1) AS rs_inn_1, 
        sum(home_score_inning_2) AS rs_inn_2, 
        sum(home_score_inning_3) AS rs_inn_3, 
        sum(home_score_inning_4) AS rs_inn_4, 
        sum(home_score_inning_5) AS rs_inn_5, 
        sum(home_score_inning_6) AS rs_inn_6, 
        sum(home_score_inning_7) AS rs_inn_7, 
        sum(home_score_inning_8) AS rs_inn_8, 
        sum(home_score_inning_9) AS rs_inn_9,
        sum(home_at_bats) AS ab,
        sum(home_hits) AS hits,
        sum(home_doubles) AS doubles,
        sum(home_triples) AS triples,
        sum(home_home_runs) AS hr,
        sum(home_rbi) AS rbi,
        sum(home_sac_hit) AS sh,
        sum(home_sac_fly) AS sf,
        sum(home_hit_by_pitch) AS hbp,
        sum(home_walks) AS bb,
        sum(home_int_walks) AS ibb,
        sum(home_strikeouts) AS k,
        sum(home_stolen_bases) AS sb,
        sum(home_caught_stealing) AS cs,
        sum(home_gidp) AS gidp,
        sum(home_catcher_interference) AS ci,
        sum(home_left_on_base) AS lob,
        sum(home_pitchers_used) AS p_used,
        sum(home_indiv_earned_runs) AS ind_er,
        sum(home_team_earned_runs) AS team_er,
        sum(home_wild_pitches) AS wp,
        sum(home_balks) AS balk,
        sum(home_putouts) AS po,
        sum(home_assists) AS ass,
        sum(home_errors) AS err,
        sum(home_passed_balls) AS pb,
        sum(home_double_plays) AS dply,
        sum(home_triple_plays) AS trply,  
        sum(visiting_at_bats) AS ab_a,
        sum(visiting_hits) AS hits_a,
        sum(visiting_doubles) AS doubles_a,
        sum(visiting_triples) AS triples_a,
        sum(visiting_home_runs) AS hr_a,
        sum(visiting_rbi) AS rbi_a,
        sum(visiting_sac_hit) AS sh_a,
        sum(visiting_sac_fly) AS sf_a,
        sum(visiting_hit_by_pitch) AS hbp_a,
        sum(visiting_walks) AS bb_a,
        sum(visiting_int_walks) AS ibb_a,
        sum(visiting_strikeouts) AS k_a,
        sum(visiting_stolen_bases) AS sb_a,
        sum(visiting_caught_stealing) AS cs_a,
        sum(visiting_gidp) AS gidp_a,
        sum(visiting_catcher_interference) AS ci_a,
        sum(visiting_left_on_base) AS lob_a,
        sum(visiting_pitchers_used) AS p_used_a,
        sum(visiting_indiv_earned_runs) AS ind_er_a,
        sum(visiting_team_earned_runs) AS team_er_a,
        sum(visiting_wild_pitches) AS wp_a,
        sum(visiting_balks) AS balk_a,
        sum(visiting_putouts) AS po_a,
        sum(visiting_assists) AS ass_a,
        sum(visiting_errors) AS err_a,
        sum(visiting_passed_balls) AS pb_a,
        sum(visiting_double_plays) AS dply_a,
        sum(visiting_triple_plays) AS trply_a
    FROM boxscore
    GROUP BY home_team, EXTRACT(YEAR FROM game_date), EXTRACT (MONTH FROM game_date);

CREATE TABLE visiting_by_m AS
    SELECT visiting_team AS team, 
        EXTRACT(YEAR FROM game_date) AS seas_yr, 
        EXTRACT(MONTH FROM game_date) AS seas_mon,
        count(*) AS gp, 
        sum(home_score) AS ra, 
        sum(visiting_score) AS rs, 
        sum(game_len_outs - 3 * ceil((game_len_outs::float / 3) / 2)) as outs,
        sum(3 * ceil((game_len_outs::float / 3) / 2)) AS outs_a, 
        sum(game_len_outs - 3 * ceil((game_len_outs::float / 3) / 2)) / 3 AS ip,
        sum(3 * ceil((game_len_outs::float / 3) / 2)) / 3 AS ip_a,
        sum(visiting_score_inning_1) AS rs_inn_1,
        sum(visiting_score_inning_2) AS rs_inn_2,
        sum(visiting_score_inning_3) AS rs_inn_3,
        sum(visiting_score_inning_4) AS rs_inn_4,
        sum(visiting_score_inning_5) AS rs_inn_5,
        sum(visiting_score_inning_6) AS rs_inn_6,
        sum(visiting_score_inning_7) AS rs_inn_7,
        sum(visiting_score_inning_8) AS rs_inn_8,
        sum(visiting_score_inning_9) AS rs_inn_9,
        sum(home_score_inning_1) AS ra_inn_1, 
        sum(home_score_inning_2) AS ra_inn_2, 
        sum(home_score_inning_3) AS ra_inn_3, 
        sum(home_score_inning_4) AS ra_inn_4, 
        sum(home_score_inning_5) AS ra_inn_5, 
        sum(home_score_inning_6) AS ra_inn_6, 
        sum(home_score_inning_7) AS ra_inn_7, 
        sum(home_score_inning_8) AS ra_inn_8, 
        sum(home_score_inning_9) AS ra_inn_9, 
        sum(visiting_at_bats) AS ab,
        sum(visiting_hits) AS hits,
        sum(visiting_doubles) AS doubles,
        sum(visiting_triples) AS triples,
        sum(visiting_home_runs) AS hr,
        sum(visiting_rbi) AS rbi,
        sum(visiting_sac_hit) AS sh,
        sum(visiting_sac_fly) AS sf,
        sum(visiting_hit_by_pitch) AS hbp,
        sum(visiting_walks) AS bb,
        sum(visiting_int_walks) AS ibb,
        sum(visiting_strikeouts) AS k,
        sum(visiting_stolen_bases) AS sb,
        sum(visiting_caught_stealing) AS cs,
        sum(visiting_gidp) AS gidp,
        sum(visiting_catcher_interference) AS ci,
        sum(visiting_left_on_base) AS lob,
        sum(visiting_pitchers_used) AS p_used,
        sum(visiting_indiv_earned_runs) AS ind_er,
        sum(visiting_team_earned_runs) AS team_er,
        sum(visiting_wild_pitches) AS wp,
        sum(visiting_balks) AS balk,
        sum(visiting_putouts) AS po,
        sum(visiting_assists) AS ass,
        sum(visiting_errors) AS err,
        sum(visiting_passed_balls) AS pb,
        sum(visiting_double_plays) AS dply,
        sum(visiting_triple_plays) AS trply, 
        sum(home_at_bats) AS ab_a,
        sum(home_hits) AS hits_a,
        sum(home_doubles) AS doubles_a,
        sum(home_triples) AS triples_a,
        sum(home_home_runs) AS hr_a,
        sum(home_rbi) AS rbi_a,
        sum(home_sac_hit) AS sh_a,
        sum(home_sac_fly) AS sf_a,
        sum(home_hit_by_pitch) AS hbp_a,
        sum(home_walks) AS bb_a,
        sum(home_int_walks) AS ibb_a,
        sum(home_strikeouts) AS k_a,
        sum(home_stolen_bases) AS sb_a,
        sum(home_caught_stealing) AS cs_a,
        sum(home_gidp) AS gidp_a,
        sum(home_catcher_interference) AS ci_a,
        sum(home_left_on_base) AS lob_a,
        sum(home_pitchers_used) AS p_used_a,
        sum(home_indiv_earned_runs) AS ind_er_a,
        sum(home_team_earned_runs) AS team_er_a,
        sum(home_wild_pitches) AS wp_a,
        sum(home_balks) AS balk_a,
        sum(home_putouts) AS po_a,
        sum(home_assists) AS ass_a,
        sum(home_errors) AS err_a,
        sum(home_passed_balls) AS pb_a,
        sum(home_double_plays) AS dply_a,
        sum(home_triple_plays) AS trply_a        
    FROM boxscore
    GROUP BY visiting_team, EXTRACT(YEAR FROM game_date), EXTRACT (MONTH FROM game_date);

CREATE TABLE total_by_month AS
    SELECT home_by_m.team AS team, 
        home_by_m.seas_yr AS seas_yr, 
        home_by_m.seas_mon AS seas_mon,
        home_by_m.gp + visiting_by_m.gp AS gp, 
        home_by_m.ra + visiting_by_m.ra AS ra, 
        home_by_m.rs + visiting_by_m.rs AS rs, 
        home_by_m.outs + visiting_by_m.outs AS outs, 
        home_by_m.outs_a + visiting_by_m.outs_a AS outs_a, 
        (home_by_m.ip + visiting_by_m.ip) AS ip, 
        (home_by_m.ip_a + visiting_by_m.ip_a) AS ip_a, 
        (home_by_m.ra + visiting_by_m.ra) / 
        ((home_by_m.ip + visiting_by_m.ip) / 9) AS ra_9,
        (home_by_m.rs + visiting_by_m.rs) / 
        ((home_by_m.ip_a + visiting_by_m.ip_a) / 9) AS rs_9,
        (home_by_m.team_er + visiting_by_m.team_er) / 
        ((home_by_m.ip + visiting_by_m.ip) / 9) AS team_era,
        (home_by_m.ind_er + visiting_by_m.ind_er) / 
        ((home_by_m.ip + visiting_by_m.ip) / 9) AS ind_era,
        (home_by_m.ra_inn_1 + visiting_by_m.ra_inn_1) as ra_inn_1,
        (home_by_m.ra_inn_2 + visiting_by_m.ra_inn_2) as ra_inn_2,
        (home_by_m.ra_inn_3 + visiting_by_m.ra_inn_3) as ra_inn_3,
        (home_by_m.ra_inn_4 + visiting_by_m.ra_inn_4) as ra_inn_4,
        (home_by_m.ra_inn_5 + visiting_by_m.ra_inn_5) as ra_inn_5,
        (home_by_m.ra_inn_6 + visiting_by_m.ra_inn_6) as ra_inn_6,
        (home_by_m.ra_inn_7 + visiting_by_m.ra_inn_7) as ra_inn_7,
        (home_by_m.ra_inn_8 + visiting_by_m.ra_inn_8) as ra_inn_8,
        (home_by_m.ra_inn_9 + visiting_by_m.ra_inn_9) as ra_inn_9,
        (home_by_m.rs_inn_1 + visiting_by_m.rs_inn_1) as rs_inn_1, 
        (home_by_m.rs_inn_2 + visiting_by_m.rs_inn_2) as rs_inn_2, 
        (home_by_m.rs_inn_3 + visiting_by_m.rs_inn_3) as rs_inn_3, 
        (home_by_m.rs_inn_4 + visiting_by_m.rs_inn_4) as rs_inn_4, 
        (home_by_m.rs_inn_5 + visiting_by_m.rs_inn_5) as rs_inn_5, 
        (home_by_m.rs_inn_6 + visiting_by_m.rs_inn_6) as rs_inn_6, 
        (home_by_m.rs_inn_7 + visiting_by_m.rs_inn_7) as rs_inn_7, 
        (home_by_m.rs_inn_8 + visiting_by_m.rs_inn_8) as rs_inn_8, 
        (home_by_m.rs_inn_9 + visiting_by_m.rs_inn_9) as rs_inn_9, 
        (home_by_m.ab + visiting_by_m.ab) AS ab,
        (home_by_m.hits + visiting_by_m.hits) AS hits,
        (home_by_m.doubles + visiting_by_m.doubles) AS doubles,
        (home_by_m.triples + visiting_by_m.triples) AS triples,
        (home_by_m.hr + visiting_by_m.hr) AS hr,
        (home_by_m.rbi + visiting_by_m.rbi) AS rbi,
        (home_by_m.sh + visiting_by_m.sh) AS sh,
        (home_by_m.sf + visiting_by_m.sf) AS sf,
        (home_by_m.hbp + visiting_by_m.hbp) AS hbp,
        (home_by_m.bb + visiting_by_m.bb) AS bb,
        (home_by_m.ibb + visiting_by_m.ibb) AS ibb,
        (home_by_m.k + visiting_by_m.k) AS k,
        (home_by_m.sb + visiting_by_m.sb) AS sb,
        (home_by_m.cs + visiting_by_m.cs) AS cs,
        (home_by_m.gidp + visiting_by_m.gidp) AS gidp,
        (home_by_m.ci + visiting_by_m.ci) AS ci,
        (home_by_m.lob + visiting_by_m.lob) AS lob,
        (home_by_m.p_used + visiting_by_m.p_used) AS p_used,
        (home_by_m.ind_er + visiting_by_m.ind_er) AS ind_er,
        (home_by_m.team_er + visiting_by_m.team_er) AS team_er,
        (home_by_m.wp + visiting_by_m.wp) AS wp,
        (home_by_m.balk + visiting_by_m.balk) AS balk,
        (home_by_m.po + visiting_by_m.po) AS po,
        (home_by_m.ass + visiting_by_m.ass) AS ass,
        (home_by_m.err + visiting_by_m.err) AS err,
        (home_by_m.pb + visiting_by_m.pb) AS pb,
        (home_by_m.dply + visiting_by_m.dply) AS dply,
        (home_by_m.trply + visiting_by_m.trply) AS trply, 
        (home_by_m.ab_a + visiting_by_m.ab_a) AS ab_a,
        (home_by_m.hits_a + visiting_by_m.hits_a) AS hits_a,
        (home_by_m.doubles_a + visiting_by_m.doubles_a) AS doubles_a,
        (home_by_m.triples_a + visiting_by_m.triples_a) AS triples_a,
        (home_by_m.hr_a + visiting_by_m.hr_a) AS hr_a,
        (home_by_m.rbi_a + visiting_by_m.rbi_a) AS rbi_a,
        (home_by_m.sh_a + visiting_by_m.sh_a) AS sh_a,
        (home_by_m.sf_a + visiting_by_m.sf_a) AS sf_a,
        (home_by_m.hbp_a + visiting_by_m.hbp_a) AS hbp_a,
        (home_by_m.bb_a + visiting_by_m.bb_a) AS bb_a,
        (home_by_m.ibb_a + visiting_by_m.ibb_a) AS ibb_a,
        (home_by_m.k_a + visiting_by_m.k_a) AS k_a,
        (home_by_m.sb_a + visiting_by_m.sb_a) AS sb_a,
        (home_by_m.cs_a + visiting_by_m.cs_a) AS cs_a,
        (home_by_m.gidp_a + visiting_by_m.gidp_a) AS gidp_a,
        (home_by_m.ci_a + visiting_by_m.ci_a) AS ci_a,
        (home_by_m.lob_a + visiting_by_m.lob_a) AS lob_a,
        (home_by_m.p_used_a + visiting_by_m.p_used_a) AS p_used_a,
        (home_by_m.ind_er_a + visiting_by_m.ind_er_a) AS ind_er_a,
        (home_by_m.team_er_a + visiting_by_m.team_er_a) AS team_er_a,
        (home_by_m.wp_a + visiting_by_m.wp_a) AS wp_a,
        (home_by_m.balk_a + visiting_by_m.balk_a) AS balk_a,
        (home_by_m.po_a + visiting_by_m.po_a) AS po_a,
        (home_by_m.ass_a + visiting_by_m.ass_a) AS ass_a,
        (home_by_m.err_a + visiting_by_m.err_a) AS err_a,
        (home_by_m.pb_a + visiting_by_m.pb_a) AS pb_a,
        (home_by_m.dply_a + visiting_by_m.dply_a) AS dply_a,
        (home_by_m.trply_a + visiting_by_m.trply_a) AS trply_a
    FROM  home_by_m, visiting_by_m
    WHERE home_by_m.team = visiting_by_m.team
        AND home_by_m.seas_yr = visiting_by_m.seas_yr
        AND home_by_m.seas_mon = visiting_by_m.seas_mon;

